# Travis CI build file.

# whitelist (branches that should be built)
branches:
  only:
    - master

language: swift

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: required

script:
 - swift build
 - swift test


before_install:
  - chmod +x ./scripts/install_swift.sh
  - ./scripts/install_swift.sh

