# Travis CI build file.

# whitelist (branches that should be built)
branches:
  only:
    - master

language: swift

jobs:
  include:
    - os: linux
      dist: bionic
      sudo: required
      language: cpp
    - os: osx
      osx_image: xcode12
      language: swift

script:
 - echo " * Script Phase"
 - env
 - . ~/.bashrc
 - swift build
 - swift test


before_install:
  - chmod +x ./.travis/install_swift.sh
  - ./.travis/install_swift.sh

